
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Decoração",
    "description": "Escolha a decoração para sua festa, e nós a montamos.",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6996815b49cce5b3d0bf02dd

###
DELETE http://localhost:3000/api/services/6996815b49cce5b3d0bf02dd

###
PUT http://localhost:3000/api/services/6996835bc807f2e63d39dc09
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "Alguma descrição",
    "price": 2500,
    "image": "https://faro.edu.br/wp-content/uploads/2018/09/229307-x-dicas-para-economizar-durante-a-faculdade-para-a-festa-de-formatura.jpg"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Endryus",
    "description": "Uma festa de aniversário",
    "budget": 9000,
    "image": "https://faro.edu.br/wp-content/uploads/2018/09/229307-x-dicas-para-economizar-durante-a-faculdade-para-a-festa-de-formatura.jpg",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição",
            "price": 3000,
            "image": "https://faro.edu.br/wp-content/uploads/2018/09/229307-x-dicas-para-economizar-durante-a-faculdade-para-a-festa-de-formatura.jpg"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição",
            "price": 1600,
            "image": "https://faro.edu.br/wp-content/uploads/2018/09/229307-x-dicas-para-economizar-durante-a-faculdade-para-a-festa-de-formatura.jpg"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/69975f2476111c717cc5bada

###
DELETE http://localhost:3000/api/parties/699791d94bc451e78cc38c6b

###
PUT http://localhost:3000/api/parties/69975f2476111c717cc5bada
Content-Type: application/json

{
    "title": "Meu evento 2",
    "author": "Endryus",
    "description": "Uma festa de aniversário",
    "budget": 10000,
    "image": "https://alphaconvites.com.br/wp-content/uploads/2023/01/festa-antes-formatura-scaled-1.jpg",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição",
            "price": 3000,
            "image": "https://faro.edu.br/wp-content/uploads/2018/09/229307-x-dicas-para-economizar-durante-a-faculdade-para-a-festa-de-formatura.jpg"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição",
            "price": 1600,
            "image": "https://faro.edu.br/wp-content/uploads/2018/09/229307-x-dicas-para-economizar-durante-a-faculdade-para-a-festa-de-formatura.jpg"
        }
    ]
}